# Generated by Django 4.2 on 2025-06-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('published_year', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('pdf_document_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
