# Generated by Django 4.2 on 2025-07-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book_total_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ai_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of AI processing', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the book', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ai_summary_audio_url',
            field=models.URLField(blank=True, help_text='URL to AI summary audio file', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='character_count',
            field=models.PositiveIntegerField(default=0, help_text='Total character count of the book'),
        ),
        migrations.AddField(
            model_name='book',
            name='estimated_audio_duration',
            field=models.PositiveIntegerField(default=0, help_text='Estimated audio duration in minutes'),
        ),
        migrations.AddField(
            model_name='book',
            name='estimated_reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='book',
            name='full_audio_url',
            field=models.URLField(blank=True, help_text='URL to full book audio file', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='last_ai_processed',
            field=models.DateTimeField(blank=True, help_text='Last time AI processing was completed', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='top_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Top keywords extracted from the book'),
        ),
        migrations.AddField(
            model_name='book',
            name='word_count',
            field=models.PositiveIntegerField(default=0, help_text='Total word count of the book'),
        ),
    ]
